[package]
name = "messing_with_inputs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mouse-keyboard-input = "0.3.7"
mouse-rs = "0.4.2"
